// source: weather.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.WeatherForecast.WeatherForecast', null, global);
goog.exportSymbol('proto.WeatherForecast.WeatherReply', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.WeatherForecast.WeatherReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.WeatherForecast.WeatherReply.repeatedFields_, null);
};
goog.inherits(proto.WeatherForecast.WeatherReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.WeatherForecast.WeatherReply.displayName = 'proto.WeatherForecast.WeatherReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.WeatherForecast.WeatherForecast = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.WeatherForecast.WeatherForecast, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.WeatherForecast.WeatherForecast.displayName = 'proto.WeatherForecast.WeatherForecast';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.WeatherForecast.WeatherReply.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.WeatherForecast.WeatherReply.prototype.toObject = function(opt_includeInstance) {
  return proto.WeatherForecast.WeatherReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.WeatherForecast.WeatherReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WeatherForecast.WeatherReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    forecastsList: jspb.Message.toObjectList(msg.getForecastsList(),
    proto.WeatherForecast.WeatherForecast.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.WeatherForecast.WeatherReply}
 */
proto.WeatherForecast.WeatherReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.WeatherForecast.WeatherReply;
  return proto.WeatherForecast.WeatherReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.WeatherForecast.WeatherReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.WeatherForecast.WeatherReply}
 */
proto.WeatherForecast.WeatherReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.WeatherForecast.WeatherForecast;
      reader.readMessage(value,proto.WeatherForecast.WeatherForecast.deserializeBinaryFromReader);
      msg.addForecasts(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.WeatherForecast.WeatherReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.WeatherForecast.WeatherReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.WeatherForecast.WeatherReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WeatherForecast.WeatherReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getForecastsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.WeatherForecast.WeatherForecast.serializeBinaryToWriter
    );
  }
};


/**
 * repeated WeatherForecast forecasts = 1;
 * @return {!Array<!proto.WeatherForecast.WeatherForecast>}
 */
proto.WeatherForecast.WeatherReply.prototype.getForecastsList = function() {
  return /** @type{!Array<!proto.WeatherForecast.WeatherForecast>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.WeatherForecast.WeatherForecast, 1));
};


/**
 * @param {!Array<!proto.WeatherForecast.WeatherForecast>} value
 * @return {!proto.WeatherForecast.WeatherReply} returns this
*/
proto.WeatherForecast.WeatherReply.prototype.setForecastsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.WeatherForecast.WeatherForecast=} opt_value
 * @param {number=} opt_index
 * @return {!proto.WeatherForecast.WeatherForecast}
 */
proto.WeatherForecast.WeatherReply.prototype.addForecasts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.WeatherForecast.WeatherForecast, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.WeatherForecast.WeatherReply} returns this
 */
proto.WeatherForecast.WeatherReply.prototype.clearForecastsList = function() {
  return this.setForecastsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.WeatherForecast.WeatherForecast.prototype.toObject = function(opt_includeInstance) {
  return proto.WeatherForecast.WeatherForecast.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.WeatherForecast.WeatherForecast} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WeatherForecast.WeatherForecast.toObject = function(includeInstance, msg) {
  var f, obj = {
    datetimestamp: (f = msg.getDatetimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    temperaturec: jspb.Message.getFieldWithDefault(msg, 2, 0),
    temperaturef: jspb.Message.getFieldWithDefault(msg, 3, 0),
    summary: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.WeatherForecast.WeatherForecast}
 */
proto.WeatherForecast.WeatherForecast.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.WeatherForecast.WeatherForecast;
  return proto.WeatherForecast.WeatherForecast.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.WeatherForecast.WeatherForecast} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.WeatherForecast.WeatherForecast}
 */
proto.WeatherForecast.WeatherForecast.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDatetimestamp(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTemperaturec(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTemperaturef(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setSummary(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.WeatherForecast.WeatherForecast.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.WeatherForecast.WeatherForecast.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.WeatherForecast.WeatherForecast} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WeatherForecast.WeatherForecast.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDatetimestamp();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getTemperaturec();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getTemperaturef();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getSummary();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional google.protobuf.Timestamp dateTimeStamp = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.WeatherForecast.WeatherForecast.prototype.getDatetimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.WeatherForecast.WeatherForecast} returns this
*/
proto.WeatherForecast.WeatherForecast.prototype.setDatetimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.WeatherForecast.WeatherForecast} returns this
 */
proto.WeatherForecast.WeatherForecast.prototype.clearDatetimestamp = function() {
  return this.setDatetimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WeatherForecast.WeatherForecast.prototype.hasDatetimestamp = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 temperatureC = 2;
 * @return {number}
 */
proto.WeatherForecast.WeatherForecast.prototype.getTemperaturec = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.WeatherForecast.WeatherForecast} returns this
 */
proto.WeatherForecast.WeatherForecast.prototype.setTemperaturec = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 TemperatureF = 3;
 * @return {number}
 */
proto.WeatherForecast.WeatherForecast.prototype.getTemperaturef = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.WeatherForecast.WeatherForecast} returns this
 */
proto.WeatherForecast.WeatherForecast.prototype.setTemperaturef = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string summary = 4;
 * @return {string}
 */
proto.WeatherForecast.WeatherForecast.prototype.getSummary = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.WeatherForecast.WeatherForecast} returns this
 */
proto.WeatherForecast.WeatherForecast.prototype.setSummary = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


goog.object.extend(exports, proto.WeatherForecast);
